### ISSUE TITLE
Mint & distribute CXN tokens

### ISSUE THREAD

**Issue by joshfraser** [cxndao/constellation#10]
I assume we'll use a standard [OpenZeppelin ERC20](https://docs.openzeppelin.com/contracts/2.x/api/token/erc20), but we still have some decisions to make:

- How many tokens to mint?
  - the [Charter](https://docs.google.com/document/d/1sCsD-QiLkXr5_uL-bL4h0PhTFoPCC6dnSbMBuKBr3OM/view#) allows up to 100M CXN to be minted 
  - 2M CXN for the DAO upfront
  - 1M CXN vest into the DAO each month
  - I may propose an amendment to the Charter to allow all the tokens to be minted upfront, but I'm waiting to see the proposed smart contract from @voska for handling the vesting first.
- Upgradeable contract? 
  - allows for flexibility in an unknown future
  - can make centralized exchange listings more difficult if that's something we care about
- Mintable?
  - Yes  
- Pausable?
  - According to the charter, the tokens will start out as nontransferable until voted otherwise
- Burnable?
  - unnecessary since we can use 0x00, but probably doesn't hurt
- Capped?
  - The charter allows for up to 100M CXN 

At Origin, we built an open-source tool for distributing tokens ([Server](https://github.com/OriginProtocol/origin/tree/master/infra/token-transfer-server), [Client](https://github.com/OriginProtocol/origin/tree/master/infra/token-transfer-client)) which might be useful if we wanted to vest token grants or want to allow people to keep their wallets anonymous:
 - used by Origin, Trust Token, NOAS, and several other projects
 - self-hosted on Heroku. can easily be customized/branded
 - token grants are managed in a SQL database (supports vesting of various lengths)
 - token holders can see their token grants in a dashboard and can withdraw to whichever wallet they want upon vesting (allows for more privacy, which might not be a requirement here)
 - uses a hot wallet on a server to distribute the tokens (some security risk) which must be topped up periodically
 
If we're not going to vest our grants & don't care about maintaining privacy, it may be simpler to manually distribute to DAO members via a one-off script.

**Comment by mattjoyal** [comment]
Following up on this issue, we will want to now focus on getting tokens out to season 0 members and then moving forward for future seasons as well.

**Comment by voska** [comment]
Here is the verified ERC-20 Smart Contract Code: https://etherscan.io/address/0x8A40D1D5Fd9c781e2eCa06C78181F038ee4f4Aa0#code
