### ISSUE TITLE
CIP Slides

### ISSUE THREAD

**Issue by jim-stanczak** [cxndao/constellation#53]
![Uploading CIP5 slide 1.png]()
![CIP5 slide 1](https://user-images.githubusercontent.com/65574926/195377415-6501aa12-06e0-4708-951e-aeebacda5aca.png)

![Uploading CIP5 slide 2.png]()
![CIP5 slide 2](https://user-images.githubusercontent.com/65574926/195377984-351f6fb9-0b93-494c-8c8d-e1fc81dba5ba.png)

**Comment by jim-stanczak** [comment]
I hope so! It was an experiment to get the slides into the CIP. If you can resolve/archive them to clean things up, by all means.

**Comment by mattjoyal** [comment]
Great okay thanks
